
version: '3.9'


services:
  db:
    image: postgres:17.2
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: intcomex_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data